version: "3"

services:

  pycalc-evaluate:
    build:
      context: .
      args:
        - MICROSERVICE=evaluate
    image: ${DOCKER_REPO}-evaluate:latest
    ports:
      - 5000:5000
    environment:
      ENV: DEV
