version: "3"

services:

  pycalc-evaluate:
    build:
      context: .
      args:
        - MICROSERVICE=evaluate
    image: jjbeto/pycalc-micro-evaluate:latest
    ports:
      - 5000:5000
    environment:
      ENV: DEV
      MICROSERVICE: evaluate
